version: "3.8"
services:
  web:
    build:
      context: ./go
    ports:
      - "8989:8989"
    volumes:
      - ./go:/app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "user=pg password=pg dbname=mydatabase host=postgres sslmode=disable"
  postgres:
    image: postgres:13
    container_name: my_postgres
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pg
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
    
